apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-geo-metricsreporter.fullname" . }}
  labels:
    {{- include "nginx-geo-metricsreporter.labels" . | nindent 4 }}
  {{- with .Values.metricsreporter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


spec:
  type: {{ .Values.metricsreporter.service.type }}
  ports:
    - port: {{ .Values.metricsreporter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-geo-metricsreporter.selectorLabels" . | nindent 4 }}
