{
 "title": "nginx geo metricreporter (Default nginx log format)",
 "description": "Custom nginx log format",
 "tags": [
  "nginx",
  "proemhteus",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Content", "query": "label_values(continentName)" },
   {
    "name": "Country",
    "query": "label_values(nginx_remote_addr_info_total{continentName=~\"^$Content\"},countryName)"
   },
   {
    "name": "City",
    "query": "label_values(nginx_remote_addr_info_total{continentName=~\"^$Content\",countryName=~\"^$Country\"},cityName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\",countryName=~\"^$Country.*$\",cityName=~\"^$City.*\"})"
    }
   ]
  },
  {
   "title": "World",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 20, "x": 4, "y": 0 },
   "valueName": "total",
   "targets": [
    { "expr": "nginx_remote_addr_info_total" }
   ]
  },
  {
   "title": "Total Continent",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_remote_addr_info_total) by (continentName)",
     "legendFormat": "{{continentName}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total [$__range]))"
    }
   ]
  },
  {
   "title": "Total Country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nginx_remote_addr_info_total) by (countryName)",
     "legendFormat": "{{countryName}}"
    }
   ]
  },
  {
   "title": "Continent",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\"}[$__range])) by (continentName)",
     "legendFormat": "{{continentName}}"
    }
   ]
  },
  {
   "title": "Country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\",countryName=~\"^$Country.*$\"}[$__range])) by (countryName)",
     "legendFormat": "{{countryName}}"
    }
   ]
  },
  {
   "title": "City",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\",countryName=~\"^$Country.*$\",cityName=~\"^$City.*\"}[$__range])) by (countryName,cityName)",
     "legendFormat": "{{cityName}} - ({{countryName}})"
    }
   ]
  },
  {
   "title": "Request Continent Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\"}[$__range])) by (continentName)",
     "legendFormat": "{{continentName}}"
    }
   ]
  },
  {
   "title": "Request Country Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\",countryName=~\"^$Country.*$\"}[$__range])) by (countryName)",
     "legendFormat": "{{countryName}}"
    }
   ]
  },
  {
   "title": "Request City Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(nginx_remote_addr_info_total{continentName=~\"^$Content.*$\",countryName=~\"^$Country.*$\",cityName=~\"^$City.*\"}[$__range])) by (countryName,cityName)",
     "legendFormat": "{{cityName}} - ({{countryName}})"
    }
   ]
  }
 ]
}